export const DEFAULT_CONFIG_FILE_NAME = 'raysconfig.js'
export const SCHEMA_FILE_NAME = 'migration.schema.prisma'
export const UTF8 = 'utf8'
export const PRISMA_MIGRATIONS_TABLE = '_prisma_migrations'
export const PRISMA_MIGRATION_NAME_COL = 'migration_name'
export const ENGINE_PARAM_PLACEHOLDER = ':?'
